plugins {
    id 'java'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.temporal:temporal-sdk:1.38.0'
    implementation 'ch.qos.logback:logback-classic:1.6.3'
    
    testImplementation 'io.temporal:temporal-testing:1.38.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.mockito:mockito-core:5.23.0'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'com.temporal.training.WorkerMain'
}

task execute(type: JavaExec) {
    mainClass = findProperty("mainClass") ?: ""
    classpath = sourceSets.main.runtimeClasspath
    if (project.hasProperty("args")) {
        args project.property("args").split(" ")
    }
}
